### ISSUE TITLE
Scans failing

### ISSUE THREAD

**Issue by DynaMc** [thugs-rumal/rumal#44]
Hi guys, 

Great work and great project here. Hopefully I can get this going, do some testing and contribute back in the future. I'm still trying to wrap my head around the project layout at the moment. 

I believe I have everything installed and working just not communicating together well enough, the thug test works fine when ran on its own. Both django projects work fine individually, queue/tasks are working but all scans fail within a few seconds. 

If someone could point me in the right direction that would be great. 

![image](https://cloud.githubusercontent.com/assets/5316899/18231379/695e34c8-7286-11e6-9215-91a75dccabc8.png)

**Comment by Dennisparchkov** [comment]
Hi,
Nice to see people giving it a go.
Are you running run_thug, consumer daemon and Mongodb for the back-end ?
If so would you mind posting what is the output in those consoles ?

**Comment by DynaMc** [comment]
Oops, just noticed I put the wrong title. Queue does get populated.

I'd run those in the background previously but I'll restart them with a console of their own. 

Ohh, just noticed the errors below. These are the output from the consoles. Minus the django thug_back console. Which had nothing as I'd already added the API key previously. 
![image](https://cloud.githubusercontent.com/assets/5316899/18231639/eb730bea-728c-11e6-96c3-7290370f2c95.png)
![image](https://cloud.githubusercontent.com/assets/5316899/18231643/fbab5b16-728c-11e6-8c46-f614c3b70b8a.png)
![image](https://cloud.githubusercontent.com/assets/5316899/18231647/0859903a-728d-11e6-9b5c-60e0d5a2d818.png)
![image](https://cloud.githubusercontent.com/assets/5316899/18231651/31c325e4-728d-11e6-9ad3-71e2100bdd17.png)
![image](https://cloud.githubusercontent.com/assets/5316899/18231654/435f3446-728d-11e6-9812-abaa7077e16d.png)

**Comment by Dennisparchkov** [comment]
It seems like the communications is working as expected, the back-end is receiving the scan and run_thug is runs the scan.
The problem is coming within run_thug  line 435 (https://github.com/thugs-rumal/rumal_back/blob/master/main/management/commands/run_thug.py#L435). (subprocess Popen)
Try removing that line and see what it does.
Are you running this on Windows or Linux ?

By the way we have a new Documentation website http://thugs-rumal.github.io/ that you can have a look at. We need to update the readme's inside Rumal.

**Comment by DynaMc** [comment]
Running on Ubuntu 16..04 LTS. 

I'm checking out the documentation thanks. 

Tried commenting it out but going to keep playing. 

Thanks for the quick responses that's awesome. I had to step away for a while but will plug away now for a bit. BTW, this was the full error last time as well, it's just my window was cutoff and I could not scroll back up since I'm working over ssh. 
![image](https://cloud.githubusercontent.com/assets/5316899/18232284/73b88626-729a-11e6-98ab-c13e3dfe4375.png)

Update, ss of when I removed that line. ( sorry to spam messages, I just want to document my process somewhere). 

![image](https://cloud.githubusercontent.com/assets/5316899/18232415/1b49cfba-729d-11e6-9f8d-d6064f5ebbc9.png)
next: 
![image](https://cloud.githubusercontent.com/assets/5316899/18232427/4d644cfa-729d-11e6-87be-69fb7c3f8c51.png)

removing the whole line:
![image](https://cloud.githubusercontent.com/assets/5316899/18232436/a827bf0a-729d-11e6-9187-16e1ef373029.png)

![image](https://cloud.githubusercontent.com/assets/5316899/18232445/de551550-729d-11e6-8919-eb89a87f928c.png)

**Comment by Dennisparchkov** [comment]
Thanks for the output from the consoles, it is always a good idea to document your processes and here is a good place. 
I think that the problem is within the `args` of the 

``` python
p = subprocess.Popen(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
```

The command run is listed within the console `Will run command: unbuffer /usr/bin/docker run --rm -a stdin -a stdout -a stderr -it pdelsante/thug-dockerfile /usr/bin/python /opt/thug/src/thug.py -D 172.17.0.1:27017 google.com
`. Have a look if this command works in a separate terminal, it is possible that one of the terms cannot be found (most likely to be `unbuffer`).

**Comment by DynaMc** [comment]
Yup, `sudo apt-get install expect` solved this issue. I was thinking it was the `args` because of the [Erno 2] but wasn't sure as you can see by the troubleshooting attempts. 

on another note, mongodb is not playing nicely so time to troubleshoot that.

**Comment by Dennisparchkov** [comment]
Great then we will update the documentation with this solution. 
If you have any other problems, you can always open up a new issue in the respective repository.

**Comment by DynaMc** [comment]
Thanks!

**Comment by tt1379** [comment]
Running Ubuntu 14.04 - I had this issue too (No such file or directory). Interestingly, I had to install **expect-dev** to resolve:

`sudo apt-get install expect-dev`

Thought it worth mentioning in case others experience the same issue.
